/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<stdio.h>
#include <stdint.h>
#include"stm32f411xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Timer Initialization
		Timer_Handle_t Tim2;
		Tim2.pTIMx = TIM2;
		Tim2.Timer_Config.Prescaler = 24;
		Tim2.Timer_Config.Period    = 100;

		Timer_Init(&Tim2);


		// Initialize GPIO as ADC1
		GPIO_Handle_t Gpio_ADC;
		Gpio_ADC.pGPIOx = GPIOA;
		Gpio_ADC.GPIO_PinConfig.GPIO_PinNumber = GPIO_P1;
		Gpio_ADC.GPIO_PinConfig.GPIO_Mode = GPIO_MODE_ANALOG;
		Gpio_ADC.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PD_PU ;

		GPIO_Init(&Gpio_ADC);

		// ADC Initialization
		ADC_Handle_t Adc1;
		Adc1.pADCx = ADC1;
		Adc1.ADC_Config.External_Trigger = EXTERN_TRIG_FEDGE;
		Adc1.ADC_Config.Extern_eve_select = TIM2_TRGO_EVENT;
		Adc1.ADC_Config.Conversion_Mode = SINGLE_MODE;
		Adc1.ADC_Config.Alignment = RIGHT_ALIGN;

		ADC_Init(&Adc1);

		// DMA Initialization
		uint8_t Membuffer;
		DMA_Handle_t DMA_2;
		DMA_2.pDMAx = DMA2;
		DMA_2.DMA_Config.Src_Dest = PERIPH_TO_MEM;
		DMA_2.DMA_Config.Peri_Port_Addr = (uint32_t*)(&(Adc1.pADCx->DR));
		DMA_2.DMA_Config.Memory_Addr = (uint32_t*)(&Membuffer);
		DMA_2.DMA_Config.Peri_Data_Size = HALF_WORD;
		DMA_2.DMA_Config.Flow_Control = PERI_FLOW;

		DMA_Config(&DMA_2);

		// Initialize GPIO as UARTs
		GPIO_Handle_t Gpio_UART1;
		Gpio_UART1.pGPIOx = GPIOA;
		Gpio_UART1.GPIO_PinConfig.GPIO_Mode = GPIO_MODE_ALF;
		Gpio_UART1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PU;
		Gpio_UART1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_HIGH_SPEED;
		Gpio_UART1.GPIO_PinConfig.GPIO_AltFuncMode = 7;

		Gpio_UART1.GPIO_PinConfig.GPIO_PinNumber = GPIO_P9;
		GPIO_Init(&Gpio_UART1);

		// UART Initialization
		USART_Handle_t UART_1;
		UART_1.pUSARTx = USART1;
		UART_1.USART_Config.USART_Baud = USART_STD_BAUD_115200;
		UART_1.USART_Config.USART_HWFlowControl = USART_HW_FLOW_CTRL_NONE;
		UART_1.USART_Config.USART_Mode = USART_MODE_ONLY_TX;
		UART_1.USART_Config.USART_NoOfStopBits = USART_STOPBITS_1;
		UART_1.USART_Config.USART_ParityControl = USART_PARITY_DISABLE;
		UART_1.USART_Config.USART_WordLength = USART_WORDLEN_8BITS;

		USART_Init(&UART_1);

		Timer_Start(TIM2, ENABLE);

		DMA_Transfer(DMA2, ENABLE);

		ADC_Start_Conversion(ADC1, ENABLE);

		USART_PeripheralControl(USART1, ENABLE);

		while(1)
		{
			if(ADC1->SR & 2)
			{
				ADC1->SR &= ~(1 << 1);
			}

			USART_SendData(&UART_1, &Membuffer, sizeof(Membuffer));

		}
}
